### ISSUE TITLE
Limited view

### ISSUE THREAD

**Issue by bluedragoons** [pluginsGLPI/uninstall#10]
En GLPI 0.85.5 avec le plugin uninstall 0.90-1.2 lors de l'utilisation du module de remplacement dans la liste déroulante "Nouveau matériel" j'ai  "limited view" et je ne vois que la première  centaine de mes ordinateurs (base GLPI avec 4700 ordinateurs).

Ce qui est d'autant plus bloquant que l'entré manuelle d'un PC n'est pas prise en compte (le recherche ne se fait que sur les 100 premiers PC)

![bugpluginuninstall](https://cloud.githubusercontent.com/assets/18657918/14781512/388e7458-0ae3-11e6-891f-c52d1c81a500.JPG)

**Comment by wawax** [comment]
Hello,

This has been fixed in my last commit.
https://github.com/pluginsGLPI/uninstall/commit/674e7ecad08babd3373c4e50b581dffee8832282
