### ISSUE TITLE
BUG : Perte des informations de Gestion d'un Ordinateur avec le module replace

### ISSUE THREAD

**Issue by bluedragoons** [pluginsGLPI/uninstall#22]
Lors de l'utilisation du plugin avec un modele de type remplacement, les informations de Gestion sont entierement éffacé pour un type ordinateur (après l'utilisation du plugin : Ordinateur -> Gestion ->Activer les informations financières et administratives) alors que l'option RAZ Budget est à Non (si oui les informations de Gestion sont aussi supprimé).

Celà ne se produit pas pour les imprimantes, les moniteurs, et les périphérique leurs informations de gestion sont bien toujours présentes.

J'ai ce comportement sur une version de GLPI en 0.85.5 et 9.1.2 avec le plugin uninstall en version 0.90-1.3 et 0.90-1.4

Pouvez vous me confirmé qu'il s'agit d'un BUG, et est il possible de le corriger ?

Merci d'avance.

**Comment by stonebuzz** [comment]
Bonjour @bluedragoons ,

voter version est vraiment ancienne, pouvez-vous mettre à jour voter GLPI en dernière version ainsi que le plugin uninstall, puis refaire un test ?

Bien cordialement

**Comment by stonebuzz** [comment]
I am closing this issue that has not evolved for a long time.
Feel free to open a new one if needed

Best regards
