### ISSUE TITLE
Option pour date de reforme

### ISSUE THREAD

**Issue by 4n63lu5** [pluginsGLPI/uninstall#33]
mettre une option pour positionner la "date de reforme" a l'instant present si elle n'est pas encore renseignée (et que l'on garde les infos de gestion)

**Comment by stonebuzz** [comment]
Hi @4n63lu5 

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards

**Comment by stonebuzz** [comment]
I am closing this issue that has not evolved for a long time.
Feel free to open a new one if needed

Best regards
