### ISSUE TITLE
Review rights management

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/uninstall#4]

**Comment by wawax** [comment]
what's wrong with right management ?

**Comment by satyan01** [comment]
hello Impossible to modify rights in profile

GLPI 9.2

**Comment by wawax** [comment]
The profile bug has been fixed here : https://github.com/pluginsGLPI/uninstall/commit/84d0160ef5c67300cfe0cd477d13d74e73bc7f1c 

I close the issue.
For more specifc issues about right management or improvements, please open another issue :)
