### ISSUE TITLE
[GLPI 9.4.1.1] + uninstall 2.6.0

### ISSUE THREAD

**Issue by b-keller** [pluginsGLPI/uninstall#46]
Hi,

I just tested to upgrade GLPI to 9.4.1.1(from 9.3.3). And I want to upgrade uninstall to 2.6.0 (from 2.5.0), in the plugins view, uninstall is marked "error / to clean" no option to upgrade. the uninstall plugin folder is in glpi plugins folder... Other plugins worked as expect (fusioninventory, badges, domains...)

Does anybody have the same problem ?
Thx

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late. Some bugs affecting plugin state have been fixed in GLPI 9.4.2, you should consider to upgrade.
Try to "clean" the plugin (it does not affect plugin data), and the use the install function to update it.

Regards

**Comment by b-keller** [comment]
Hi,

Me too... (for the late). I ran again the upgrade process from GLPI 9.3.3 to 9.4.2 and there are no problems any more.

I close the issue.

Thx
