### ISSUE TITLE
The way to empty list when have been select wrong computers for replacement or uninstall

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/uninstall#59]
GLPI Version: 9.5.7
Plugin version: 2.7.2

There should be an option to remove or clear the list of selected computers for the Replace (Replacement) template. Sometimes I accidentally choose a computer, or you made a mistake when choosing, how can I remove that selection and not appear in the following list?

![image](https://user-images.githubusercontent.com/56606032/159940139-9d6f16ae-5043-4ee2-a7cc-fea5995cbba3.png)

**Comment by stonebuzz** [comment]
Hi @jcervantes-sipecom 
can you try this
https://github.com/pluginsGLPI/uninstall/pull/78

Best regards

**Comment by jcervantes-sipecom** [comment]
Hi @stonebuzz, thanks for your reply, I did the changed, the remove option delete the row visually, but not internally I guess. 

Look what I mean:

1. I select 2 computers, and did a uninstallation replacement:
![image](https://user-images.githubusercontent.com/56606032/214960494-36bbf242-785e-4a4c-8487-dd426216d38d.png)

![image](https://user-images.githubusercontent.com/56606032/214960801-ee5cbd04-b492-42bb-b3c2-b70c8f63e792.png)

2. I removed the extra computer, but when I search in the dropdown the removed computer, it didn't appear:
![image](https://user-images.githubusercontent.com/56606032/214961421-9b89a478-8fdb-493c-b615-9a72b98e5906.png)

3. Also if I go back and then deselected the extra computer selected, and repeat the uninstallation replacement, the computer stills appears:
![image](https://user-images.githubusercontent.com/56606032/214961673-ffd943b8-647c-485e-bd56-4ce30458cdb4.png)

![image](https://user-images.githubusercontent.com/56606032/214962372-ff09ca8b-43ab-4a93-a2d1-75d2fce86296.png)


Also the remove icon didn't appear but it works:
![image](https://user-images.githubusercontent.com/56606032/214962035-c1880da7-cff0-41a0-ae68-e7a0023e53d2.png)

**Comment by stonebuzz** [comment]
I just saw that you were still in version 9.5.7.

You have to update your GLPI to version 10 because pull request use 2.8.1 version of uninstall plugin

Best regards
