### ISSUE TITLE
 Undefined index: version in /var/www/html/glpi/marketplace/uninstall/inc/model.class.php

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/uninstall#60]
GLPI Version: 9.5.7
Plugin version: 2.7.2

I'm getting this error:
PHP Notice (8): Undefined index: version in /var/www/html/glpi/marketplace/uninstall/inc/model.class.php at line 418
![image](https://user-images.githubusercontent.com/56606032/160002256-ff43da7f-ce68-4bfb-94dd-e57789c82c21.png)

In this file in this line, it's:

> $plug = new Plugin();
>       if ($plug->isActivated('PDF')
>           && $plug->fields['version'] >= '0.7.1') { -- line 418

How to resolve it?

**Comment by jcervantes-sipecom** [comment]
Obviously I have plugin PDF installed and activated:

![image](https://user-images.githubusercontent.com/56606032/160014862-d7aac0cc-cc18-4d9f-a477-9b6e7d561816.png)

**Comment by cedric-anne** [comment]
Should be fixed by #61 .
