### ISSUE TITLE
Replacement model, do not remove the old material

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/uninstall#7]
Add an option to "Archiving method of the old material" : Don't delete.

**Comment by wawax** [comment]
what do you mean ?

**Comment by flegastelois** [comment]
Actually we have 2 options in "Archiving method of the old material" : 
* Delete + Comment
* OR Purge + CSV/PDF Archiving

It would be nice if we have a third option "Don't delete, don't purge, just Comment".

**Comment by wawax** [comment]
done in commit 47657b397819e79b89b88b9712391286e557beba
