### ISSUE TITLE
Comportement bizarre pour mise à niveau 2.2

### ISSUE THREAD

**Issue by tbarrau** [pluginsGLPI/uninstall#8]
Bonjour,

Je viens de faire un test sur un env. de dev.
Maj GLPI 0.84 vers 0.85.5
Le plugin s'affiche toujours en 2.2, donc il ne me demande pas de mettre à niveau mais juste de l'activer .

Une fois activé, il n'apparait ni dans le menu Plugin ni aucun autre.

Je ne le retrouve que dans les fiches ordinateurs, et après un essai il n'effectue pas toutes les actions (ci dessous l'historique du poste):
"Volume Verrouiller un élément : Volume (C: (294)) 
 Volume Verrouiller un élément : Volume (Applis (51)) 
 Domaine Changement de kyron.local (10) par   (0) 
 Lieu Changement de   (0) par   () 
 Statut Changement de En Production (3) par En Stock (4) 
 Utilisateur Changement de Administrateur (30) par   (0) 
 Usager Changement de Administrateur par "

Egalement pas de boutons pour valider le changement de droits dans la gestion de profil

merci

**Comment by wawax** [comment]
Please retry with version 0.90-1.2

**Comment by tbarrau** [comment]
Bonjour wawax
Merci pour ce retour :+1: 

Après essai voici mes retours : 
- La mise à jour après upgrade de GLPI 0.84 avec uninstall 2.2 vers GLPI 0.85 avec uninstall 0.90-1.2 ne fonctionne pas et affiche "Le site Web ne peut pas afficher la page" sous IE, et "Traitement en cours..." (page /front/plugin.form.php" sur Firefox)
- J'ai par contre essayé une désinstallation, installation, activation et ça fonctionne. Par contre cela nécessite un reparamétrage complet.
- Une fois désinstaller et réinstaller par contre le logiciel fonctionne très bien après coup et il s'affiche bien partout.

Est-ce que je peux faire un extract de quelque chose pour t'aider ?

Merci pour tout.

**Comment by stonebuzz** [comment]
Bonjour @tbarrau  ,

voter version est vraiment ancienne, pouvez-vous mettre à jour voter GLPI en dernière version ainsi que le plugin uninstall, puis refaire un test ?

Bien cordialement

**Comment by stonebuzz** [comment]
I am closing this issue that has not evolved for a long time.
Feel free to open a new one if needed

Best regards
