### ISSUE TITLE
Replace New Item Dropdown doesn't search item name, not charge all items, and repeat items after more or less 50 list items

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/uninstall#86]
GLPI Version: 10.0.9
Plugin Version: 2.9.0

I'm getting 2 issues:

1) When I try to replace a Computer, and try to search the Computer Name in the dropdown, it doesn't search at all:

![image](https://github.com/pluginsGLPI/uninstall/assets/56606032/5588959f-3cee-41e0-b5a2-cf9108d6b554)

The computer already exists:

![image](https://github.com/pluginsGLPI/uninstall/assets/56606032/e1ed6c23-f40e-4c90-933c-0b753eb22d54)

2) Also when I search a computer, after scroll down more or less 50 computers, it repeats again the first computer, so it doesn't list all computers, look the navigation bar it's at the begining, the first computer start with the AU2 name:

![image](https://github.com/pluginsGLPI/uninstall/assets/56606032/79529cb3-52c6-45af-8182-6c218dd253a8)

When I scroll down after 50 computers, it resets the computer list, the last computer name showing start with the name CM78 and show again the first computer, and this repeat infinitely if I continue to scroll down:

![image](https://github.com/pluginsGLPI/uninstall/assets/56606032/73d6b068-d892-4098-a974-9c152b7d15b1)

When actually my last computer start with WIN*:

![image](https://github.com/pluginsGLPI/uninstall/assets/56606032/d891f3d9-c5b2-4e59-a86a-9131c0ab7227)

**Comment by SilvMH** [comment]
+1 Please
